name: 'action1'
description: 'Action 1'
inputs:
  input1:  # id of input
    description: 'Input 1'
    required: true
    default: 'empty'
runs:
  using: "composite"
  steps:
    - name: script
      run: |
        echo "---"
        az account show 
        echo "input=${{ inputs.input1 }}"
    - name: Trigger Workflow
      uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.input1 }}
        script: |
          github.rest.actions.createWorkflowDispatch({
            owner: 'tvdvoorde',
            repo: 'action1',
            workflow_id: 'subaction.yaml',
            ref: 'main',
            inputs: {
              inputkey1: 'inputvalue1' 
            },              
          })
