name: 'action1'
description: 'Action 1'
inputs:
  input1:  # id of input
    description: 'Input 1'
    required: true
    default: 'empty'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - run: echo "-ACTION-"
      shell: bash
    - run: az account show 
      shell: bash
    - id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: date
      shell: bash
    - name: Trigger Workflow
      uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.input1 }}
        script: |
          github.rest.actions.createWorkflowDispatch({
            owner: 'tvdvoorde',
            repo: 'action1',
            workflow_id: 'subaction.yaml',
            ref: 'main',
            inputs: {
              inputkey1: 'inputvalue1' 
            },              
          })
