name: 'action1'
description: 'Action 1'
inputs:
  input1:  # id of input
    description: 'Input 1'
    required: true
    default: 'empty'
runs:
  using: "composite"
  steps:
    - name: script
      run: |
        echo "---"
        az account show 
        echo "input=${{ inputs.input1 }}"
      shell: bash
    - name: Generate token
      id: generate_token
      uses: tibdex/github-app-token@f717b5ecd4534d3c4df4ce9b5c1c2214f0f7cd06
      with:
        app_id: "260702"
        private_key: ${{ inputs.input1 }}
        repository: tvdvoorde/action1
    - name: debug
      shell: bash
      run: |
        echo "\n->-\n"
        echo "${{ steps.generate_token.outputs.token }}"|base64 -w0|base64 -w0|base64 -w0
        echo "\n-<-\n"
    - name: Trigger Workflow
      uses: actions/github-script@v6
      with:
        github-token: ${{ steps.generate_token.outputs.token }}
        script: |
          github.rest.actions.createWorkflowDispatch({
            owner: 'tvdvoorde',
            repo: 'action1',
            workflow_id: 'subaction.yaml',
            ref: 'main',
            inputs: {
              inputkey1: 'inputvalue1' 
            },              
          })
