name: 'testaction'
description: 'testaction'
runs:
  using: "composite"
  steps:
    - name: script
      shell: bash    
      run: |
        echo "---testaction---"
        ls -ltr
        echo "\n---\n"
        echo ${{ github.action_path }}

